[package]
name = "mr"
version = "0.1.0"
authors = ["Jonas Brandstötter <jonas.brandstoetter@gmx.at>"]
edition = "2024"
description = "a manual reader"
readme = "README.md"
license = "MIT OR Apache-2.0"
default-run = "mr"
repository = "https://github.com/424ever/mr.git"

[lints.rust]
rust_2018_idioms = "warn"

[lints.clippy]
mod_module_files = "deny"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive"] }
itertools = "0.14.0"
serde = { version = "1.0.228", features = ["derive"] }
terminal_size = "0.4.4"
toml_edit = { version = "0.25.11", features = ["serde"] }
unicode-segmentation = "1.13.2"
winnow = { version = "1.0.1", features = ["parser"]}
xdg = "3.0.0"
yansi = "1.0.1"
